# Dataset paths
path: C:/Users/Edrian/Documents/VSCodeProjects/CaniScan/dataset

# Training images
train: ../train/images

# Validation images
val: ../valid/images

# Test images (optional but recommended)
test: ../test/images

# Number of classes
nc: 4

# Class names
names: ['allergic dermatitis', 'fungal infection', 'hotspot', 'mange']
