# Dataset paths (use forward slashes to avoid Windows escape issues)
path: C:/Users/Edrian/Documents/VSCodeProjects/CaniScan/yolov8/dataset

# Training images
train: C:/Users/Edrian/Documents/VSCodeProjects/CaniScan/yolov8/dataset/train

# Validation images
val: C:/Users/Edrian/Documents/VSCodeProjects/CaniScan/yolov8/dataset/train

# Number of classes
nc: 3

# Class names
names: ["ringworm", "hotspot", "mange"]
